# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Under Bed Comics
email:
description: 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://under-bed-comics.com" # the base hostname & protocol for your site
twitter_username:
github_username:  under-bed-comics

# Build settings
markdown: kramdown
